#!/usr/bin/env bash
# Bash script that configures a server to listen on port 80
sudo apt-get update
sudo apt-get -y install ufw
#sudo apt-get upgrade iptables
sudo ufw enable
sudo ufw allow 'NGINX HTTP'
config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Make site accessible from http://localhost/
        server_name localhost;
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files \$uri \$uri/ =404;
                # Uncomment to enable naxsi on this location
                # include /etc/nginx/naxsi.rules
        }
}"
sudo bash -c "echo -e '$config' > /etc/nginx/sites-enabled/default "
sudo service nginx restart
