#!/usr/bin/env bash
#wrote a script that makes nginx listen on port 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo bash -c "echo 'fakepid' > /run/nginx.pid"
