#!/usr/bin/env bash
# A Bash script that displays a list of currently running process
#es.
#Must show all processes, for all users, including those which mi
#ght not have a TTY
#Display in a user-oriented format
#Show process hierarchy
ps auxf
