#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 100.
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format
for ((fibnum=1; fibnum <= 100; fibnum++));
do
	if ((fibnum % 3 == 0 && fibnum % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif ((fibnum % 3 == 0))
	then
		echo "Fizz"
	elif ((fibnum % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$fibnum"
	fi
done
