#!/usr/bin/env bash
#  Bash script that displays Best School 10 times, but for the 9t
#h iteration, displays Best School and then Hi on a new line.
i=1
while [ $i -le 11 ]
do
	if [ $i -eq 10 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
	
done
