#!/usr/bin/env bash
#A script Fix this container so that Nginx is running as the nginx user.
pkill  apache2
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
service nginx reload
